version: '3'
services:
  client:
    build:
      context: ./grpc-web
    image: bench-client
    container_name: bench-client
    networks: 
      - benchmark
    environment: 
      BENCHMARK_TIME: 30000

networks:
  benchmark:
